/**
 * @file version.h
 * @brief Project Version. DO NOT EDIT THIS FILE DIRECTLY (Edited in "scripts/update_version.py")
 * 
 */

#ifndef SOFTWARE_VERSION_MAJOR
  #define SOFTWARE_VERSION_MAJOR 1
#endif
#ifndef SOFTWARE_VERSION_MINOR
  #define SOFTWARE_VERSION_MINOR 0
#endif
#ifndef SOFTWARE_VERSION_FIX
  #define SOFTWARE_VERSION_FIX 0
#endif
#ifndef SOFTWARE_VERSION_BUILD
  #define SOFTWARE_VERSION_BUILD 3
#endif
#ifndef SOFTWARE_BUILD_TIME
  #define SOFTWARE_BUILD_TIME "2023-10-31 19:18:45.130688"
#endif
#ifndef SOFTWARE_AUTHOR
  #define SOFTWARE_AUTHOR "larry"
#endif
#ifndef SOFTWARE_GIT_COMMIT
  #define SOFTWARE_GIT_COMMIT "->"
#endif
